[tool.poetry]
name = "cute-wayland-recorder"
version = "0.1.0"
description = "A small graphical screen recorder for Wayland, leveraging wf-recorder and slurp"
authors = ["Maor Kadosh <qoev@protonmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.7 <=3.9"
PySide2 = "^5.15.1"

[tool.poetry.scripts]
cute-wayland-recorder = "cute_wayland_recorder.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
